version: 2.1
orbs: 
  heroku: circleci/heroku@0.0.6
jobs:
  format:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Check code formatting
          command: yarn run format-ci
  test:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Run test suite
          command: yarn run test-ci
  build:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Build client application
          command: yarn run build
  audit:
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Audit dependencies
          command: yarn run audit
  deploy_dev: 
    docker:
      - image: circleci/node:10.14  
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git: 
          app-name: swoptop-dev
          only-branch: master
  deploy_prod: 
    docker:
      - image: circleci/node:10.14  
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git: 
          app-name: swoptop-prod
          only-branch: master
workflows:
  version: 2
  deploy_dev_promote_prod: 
    jobs: 
      - test
      - build
      # - audit
      - format
      - deploy_dev: 
          requires: 
            - build
            # - audit
            - test
            - format            
      - hold:
          type: approval
          requires: 
            - deploy_dev     
      - deploy_prod: 
          requires: 
            - hold      
